### PR TITLE
Adding support for .NET 7

### LINKED ISSUE #246: .Net 7 Compatibility please!

### PR DESCRIPTION
**Pull request by Logerfo**
Closes #246.

### CODE REVIEW

**Comment by pavel-b-novikov** [comment]
I will build and upload new version as soon as possible

**Comment by lukedukeus** [comment]
This is great, can you release a nuget package so we can use it?

**Comment by kfrancis** [comment]
@pavel-b-novikov Same here, would you mind pushing a release?

**Comment by pyramid-scheme-ceo** [comment]
@pavel-b-novikov also bumping for release please

**Comment by kfrancis** [comment]
> @pavel-b-novikov also bumping for release please

I have spoken with him, he's just a bit busy but he'll be back soon.

**Comment by mavilla-dev** [comment]
Hi all, thanks for all your hard worked around this. Any chance we could get this released by the end of the week?

**Pull request merged**
