### PR TITLE
use Microsoft.AspNetCore.App framework for rtcli

### PR DESCRIPTION
**Pull request by zivillian**
The fix is to [switch the Project SDK to `Microsoft.NET.Sdk.Web`](https://github.com/reinforced/Reinforced.Typings/commit/cb6a2dcacfbb692af85d01133b1e66899298252d), all the other changes revert the workarounds which are no longer needed. Since rtcli is trying to load aspnetcore assemblies anyway, it must be installed on the build machine, so there should be no additional dependency.

I've succesfully tested this with a local built nuget package against a aspnetcore3.1 project whith the following tools and sdk:

```
>dotnet --version
3.1.301

>dotnet --list-runtimes
...
Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

>dotnet --list-sdks
2.1.802 [C:\Program Files\dotnet\sdk]
3.0.101 [C:\Program Files\dotnet\sdk]
3.1.301 [C:\Program Files\dotnet\sdk]

>dir "C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref"
...
17.12.2019  12:30    <DIR>          3.0.1
04.04.2020  19:01    <DIR>          3.1.3
```

The relevant change in the nuget package output is inside `tools\netcoreapp3.1\rtcli.runtimeconfig.json`
```diff
{
   "runtimeOptions": {
     "tfm": "netcoreapp3.1",
     "framework": {
-      "name": "Microsoft.NETCore.App",
+      "name": "Microsoft.AspNetCore.App",
       "version": "3.1.0"
+    },
+    "configProperties": {
+      "System.GC.Server": true
     }
   }
 }
```

Fixes: #173 #174 #156 #137

### CODE REVIEW

**Comment by pavel-b-novikov** [comment]
Great job, thank you!

Will it work with non-web assemblies? I mean, I use RT for some things that are not referencing Web SDK. Are you sure that it will not fail in this case? Or we have to build 2 separate versions of rtcli?

**Comment by zivillian** [comment]
As long as aspnetcore ist installed it should work, but I will test tomorrow.

**Comment by zivillian** [comment]
I've succesfully tested this with an `netcoreapp3.1` and `netcoreapp3.0` console application targeting `Microsoft.NET.Sdk`.

**Comment by pavel-b-novikov** [comment]
Well, okay, let's try it

**Comment by jannikbuschke** [comment]
Does this fix https://github.com/reinforced/Reinforced.Typings/issues/156 and all current issues with new dotnet core versions?

**Comment by MartinM85** [comment]
When will be a new nuget package available?

**Comment by pavel-b-novikov** [comment]
Near the weekend I will take it.

**Comment by GreenAirplane** [comment]
@pavel-b-novikov, any chance that you will publish a new nuget version with this fix soon? I've just built it locally, installed it as a local package and it completely resolved #156 for me (without `RtAssemblyReplacements`)! As far as I understand, this fix should help to a lot of your users! Thank you in advance!

**Comment by pavel-b-novikov** [comment]
I'm on it

**Pull request merged**
