### PR TITLE
.Net 5 is supported

### PR DESCRIPTION
**Pull request by radiosterne**

### CODE REVIEW

**Comment by pavel-b-novikov** [comment]
С возвращением :) 
Have you tried to build package via cake?

**Comment by radiosterne** [comment]
Спасибо :)

Yes, I've built it via cake, ensured that build has finished correctly (except for signing step, which I disabled), and used for my local testing process the resulting nupkg

**Comment by radiosterne** [comment]
Thank you for such a fast merge :) I've forgot to mention that I hadn't incremented package version — should I do it, or you will?

**Comment by pavel-b-novikov** [comment]
I will test it locally myself and will increase version.

**Pull request merged**
